<Anton/first commit>
FausT-VX/FitnessTracker pull request #1
Opened 2024-04-05 13:07 UTC by FausT-VX

2024-04-05 13:42 UTC, dirtymew requested changes
Привет Антон

Хорошая работа - верно определил интерфейс и использовал встраивания

Нужно немного доделать - чтобы все было по заданию

2024-04-05 13:42 UTC, dirtymew commented on main.go
> +	return s.Training.TrainingInfo()
тут неверно см задание 

Для реализации этого метода для структуры Swimming{} нужно полностью переопределить TrainingInfo() с учетом того, как расчитывается средняя скорость для плавания, дистанция и так далее. Реализация TrainingInfo() для Swimming{} будет похожа на реализацию TrainingInfo() для Training{}, но с иcпользованием методов для Swimming{}.

2024-04-05 13:42 UTC, dirtymew commented on main.go
> +	calInMin := CaloriesWeightMultiplier*w.Weight + (speedSquare/height)*CaloriesSpeedHeightMultiplier*w.Weight
тут возможно деление на 0

2024-04-05 15:15 UTC, dirtymew approved these changes
Антон

зачет 

удачи в обучении

2024-04-06 14:29 UTC, FausT-VX commented
> Антон
> 
> зачет
> 
> удачи в обучении

Спасибо!

2024-12-16 09:01 UTC, merged